### ISSUE TITLE
Android Basics: Navigation backstack

### ISSUE THREAD

**Issue by detinsley1s** [google-developer-training/android-basics-kotlin-cupcake-app#8]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-navigation-backstack

**In which task and step of the codelab can this issue be found?**
5. Send the order

**Describe the problem**
In the code for the full sendOrder() method, the last argument for getString() that will be placed in the orderSummary variable is sharedViewModel.priceString.value.toString(), however this should be sharedViewModel.price.value.toString().

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![wrong_variable_name](https://user-images.githubusercontent.com/10083390/111944043-bfad3000-8aa4-11eb-9cd9-c077381eea6e.png)

**Comment by Rayishere** [comment]
This problem is still existing, however, the source code on GitHub is right
Link: [fun sendorder()](https://github.com/google-developer-training/android-basics-kotlin-cupcake-app/blob/main/app/src/main/java/com/example/cupcake/SummaryFragment.kt)
![image](https://user-images.githubusercontent.com/25098436/118743242-89154b00-b884-11eb-8675-cd55e808a37c.png)

**Comment by jhansitavva** [comment]
@ @detinsley1s 
Thank you so much for reporting this issue. This is fixed and will be published soon.
